baseURL:
disableKinds: [section, taxonomy, term, RSS, sitemap, 404]
enableRobotsTXT: true
languageCode: en

title: Online Resume
theme: online-resume

markup:
  goldmark:
    renderer:
      unsafe: true          # allow HTML tags in markdown

params:
  # Custom
  open: true                # show or hide your resume
  allowSearchEngines: true  # allow your resume indexing by search engine, 'true' or 'false'
  analytics:
    google:                 # google analytics
    cloudflare:             # cloudflare analytics
    umami:
      script:               # umami analytics script src
      websiteID:            # umami analytics website id
      domains:              # umami analytics domains
  description:
  openGraph:
    enable: true                # enable open graph meta tags
    image: /images/profile.png  # open graph image path

  # Style
  textDirection: ltr        # text direction, 'ltr' or 'rtl'
  dateFormat: 2006-01-02    # date format
  themeColor: "#1DA1F2"     # your favorite theme color
  contactDelimiter: "·"     # contact delimiter, '·', '/' or '|'
  sectionIcon: true         # section title icon, 'true' or 'false'
  sectionTitle: uppercase   # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
  sectionAlign: start       # section title align, 'start', 'end' or 'center'
  sectionLine: dashed       # section title line, 'solid', 'dashed' or 'none'
  sectionBackground: false  # section title backound, 'true' or 'false'
  skillLevelIcon: lightbulb # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
  linkIcon: true            # show link icon, 'true' or 'false'
  siteFooter: true          # show site footer, 'true' or 'false'
